name: Scrape

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # 8 a.m. every day UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Prepare the environment
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Step 2: Install requirements, so Python script can run
    - name: Install requirements
      run: python -m pip install pandas selenium requests bs4 webdriver-manager
    # Step 3: Run the Python script    
    - name: Run scraper
      run: python scrape.py     
    # Step 4: Commit and push
    - name: Commit and push
      run: |-
        git pull
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
